# Generated by Django 3.1.2 on 2020-11-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201101_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'OrderDetails'},
        ),
    ]
