# Generated by Django 3.1.2 on 2020-11-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0004_auto_20201103_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='slug',
            field=models.SlugField(default='', max_length=254, unique=True),
        ),
    ]
