# Generated by Django 3.1.2 on 2020-11-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0008_auto_20201104_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
